### PR TITLE
Add create manifest functionality

### PR DESCRIPTION
**Pull request by ptrebert**
This PR introduces substantial changes:
- add functionality to automatically create a complete file manifest (prepared only during pipeline dry runs, necessary jobs then executed during next actual run)
- add docs/ subfolder, documentation starts to get lengthy; may need further splits in the future
- include some explicit comments in pyutils to logically group functions (also move ref-con related functions here now to get rid of snakemake linting messages)
- required to extract dry run information: introduced new commons module as workflow "staging" area: perform task before actual workflow execution starts

### CODE REVIEW

**Comment by svenwillger** [comment]
I went through the script and on first pass I only found a typo in one file (docs/README.md, line 49, 1st word should be "executed").

When testing the workflow without reference container it works flawless; however, it should be mentioned in the section "Documentation for developers" in the README again, that the dryrun has to be run at least once first. Otherwise the workflow just stops in the middle of the testrun and then stops the workflow with an error because the manifest.tsv file is not being created and no further information. 

If running the snaketest workflow with a reference container, put in wd/test_vo.sif the first dryrun gives the following output:
```
Job stats:
job                         count    min threads    max threads
------------------------  -------  -------------  -------------
create_manifest                 1              1              1
create_test_file                1              1              1
dump_config                     1              1              1
refcon_cache_manifests          1              1              1
refcon_dump_manifest            1              1              1
refcon_run_get_file             1              1              1
run_tests                       1              1              1
test_find_script_fail           1              1              1
test_find_script_success        1              1              1
test_git_labels                 1              1              1
test_log_functions              2              1              1
test_rsync_f2d                  1              1              1
test_rsync_f2f                  1              1              1
test_rsync_fail                 1              1              1
trigger_tests                   1              1              1
total                          16              1              1

Reasons:
    (check individual jobs above for details)
    input files updated by another job:
        refcon_cache_manifests, refcon_run_get_file, run_tests, test_find_script_fail, test_find_script_success, test_git_labels, test_rsync_f2d, test_rsync_f2f, test_rsync_fail, trigger_tests
    missing output files:
        create_manifest, create_test_file, dump_config, refcon_cache_manifests, refcon_dump_manifest, refcon_run_get_file, test_find_script_fail, test_find_script_success, test_git_labels, test_log_functions, test_rsync_f2d, test_rsync_f2f, test_rsync_fail, trigger_tests

This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.
```

The second dryrun gives the following output:
```
Job stats:
job                         count    min threads    max threads
------------------------  -------  -------------  -------------
accounting_file_md5_size       12              1              1
accounting_file_sha256         12              1              1
create_manifest                 1              1              1
create_test_file                1              1              1
dump_config                     1              1              1
refcon_cache_manifests          1              1              1
refcon_dump_manifest            1              1              1
refcon_run_get_file             1              1              1
run_tests                       1              1              1
test_find_script_fail           1              1              1
test_find_script_success        1              1              1
test_git_labels                 1              1              1
test_log_functions              2              1              1
test_rsync_f2d                  1              1              1
test_rsync_f2f                  1              1              1
test_rsync_fail                 1              1              1
trigger_tests                   1              1              1
total                          40              1              1

Reasons:
    (check individual jobs above for details)
    input files updated by another job:
        accounting_file_md5_size, accounting_file_sha256, create_manifest, refcon_cache_manifests, refcon_run_get_file, run_tests, test_find_script_fail, test_find_script_success, test_git_labels, test_rsync_f2d, test_rsync_f2f, test_rsync_fail, trigger_tests
    missing output files:
        accounting_file_md5_size, accounting_file_sha256, create_manifest, create_test_file, dump_config, refcon_cache_manifests, refcon_dump_manifest, refcon_run_get_file, test_find_script_fail, test_find_script_success, test_git_labels, test_log_functions, test_rsync_f2d, test_rsync_f2f, test_rsync_fail, trigger_tests

This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.
```

and when doing the actual run this is the output (also true after the just the 1st dryrun):
```
snakemake --cores 1          --config devmode=True     --directory wd/     --configfiles config/testing/params_refcon.yaml     --snakefile workflow/snaketests.smk  
Building DAG of jobs...
FileNotFoundErrorin line 493 of /home/sven/Git/core-unit-bioinformatics/add_manifest/template-snakemake/workflow/rules/commons/02_pyutils.smk:
Reference container manifest cache does not exist: proc/.cache/refcon/refcon_manifests.cache
  File "/home/sven/Git/core-unit-bioinformatics/add_manifest/template-snakemake/workflow/rules/commons/05_refcon.smk", line 35, in <lambda>
  File "/home/sven/Git/core-unit-bioinformatics/add_manifest/template-snakemake/workflow/rules/commons/02_pyutils.smk", line 493, in refcon_find_container
```
Unfortunately, I couldn't figure out, yet, why the `proc/.cache/refcon/refcon_manifests.cache` wasn't created. Maybe you can find it faster, but I'll still try to find the issue.

**Comment by sci-kai** [comment]
I also checked the changes and did not find an error.
Running the workflow w/o reference container worked as expected, with all manuscript files. These are also very comprehensive.

When running with reference containers I experience the exact same issue as Sven reported. The "proc/.cache" folder is also non-existing, so I guess that the error lies within the manifest dumping step. I also could not figure it out yet.

**Comment by ptrebert** [comment]
thanks a lot for checking and pointing that out. It seems the series of executions is (was) the problem, which I now solved by adding one of the dreaded Snakemake checkpoints for creating the reference container manifest cache. Please confirm that it does now what it is supposed to do.

**Comment by svenwillger** [comment]
Now the pipeline is doing what it's supposed to do. 

edit: I couldn't find the updated reference container config to create the container test_v1.sif. I had to modify the snaketest.smk to run with "my" test_v0.sif

**Comment by sci-kai** [comment]
I just created the reference test container v1 with the reference container repository version with your new commit without any changes and it directly worked nicely as supposed. From my side it can be merged now.

**Pull request merged**
